<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Nuri.WPF\Nuri.WPF.csproj" />
    <EmbeddedResource Include="styles\embedded-default.yml" />
    <None Include="styles\*.yml" Exclude="styles\embedded-default.yml" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
